name: Build & Test

on: push

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn --non-interactive --no-lockfile
      - name: Build
        run: yarn predeploy
      - name: Test
        run: yarn test:nowatch