name: Release
on:
  # can be triggered manually
  workflow_dispatch:
  # on push with tag
  push:
   tags:
     - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  gh-release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test:nowatch
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#github-tests'
        if: always()

  npm-publish:
    needs: gh-release
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        run: npm publish --access public
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

  gh-pages-deploy:
    needs: npm-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm clean-install
      - run: git config --global user.name "poplingue"
      - run: git config --global user.email "paulinegc@protonmail.com"
      - run: git remote set-url origin https://github.com/dataesr/react-dsfr.git
      - run: npm run deploy
        env:
          GH_PAT: ${{secrets.GH_PAT}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

